-- MySQL Script generated by MySQL Workbench
-- Fri Dec 23 23:14:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_BANCO
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_BANCO` ;

-- -----------------------------------------------------
-- Schema DB_BANCO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_BANCO` DEFAULT CHARACTER SET utf8 ;
USE `DB_BANCO` ;

-- -----------------------------------------------------
-- Table `DB_BANCO`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`Cliente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `nacimiento` DATE NULL,
  `cuenta` VARCHAR(18) NULL,
  `clave` VARCHAR(18) NULL,
  `tarjeta` VARCHAR(16) NULL,
  `celular` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`Bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`Bancos` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`Bancos` (
  `idBancos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idBancos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`Tipo_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`Tipo_transaccion` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`Tipo_transaccion` (
  `idTipo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`Estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`Estados` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`Estados` (
  `idEstados` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`Errores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`Errores` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`Errores` (
  `idErrores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idErrores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`Transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`Transaccion` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`Transaccion` (
  `idTransaccion` INT NOT NULL,
  `idCliente` INT NULL,
  `idBanco` INT NULL,
  `monto` DECIMAL NULL,
  `tipo` INT NULL,
  `estado` INT NULL,
  `errorT` INT NULL DEFAULT NULL,
  `generada` DATE NULL,
  PRIMARY KEY (`idTransaccion`),
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `IdBanco_idx` (`idBanco` ASC) VISIBLE,
  INDEX `tipo_idx` (`tipo` ASC) VISIBLE,
  INDEX `estado_idx` (`estado` ASC) VISIBLE,
  INDEX `error_idx` (`errorT` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `DB_BANCO`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdBanco`
    FOREIGN KEY (`idBanco`)
    REFERENCES `DB_BANCO`.`Bancos` (`idBancos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `DB_BANCO`.`Tipo_transaccion` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estado`
    FOREIGN KEY (`estado`)
    REFERENCES `DB_BANCO`.`Estados` (`idEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `error`
    FOREIGN KEY (`errorT`)
    REFERENCES `DB_BANCO`.`Errores` (`idErrores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`log_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`log_cliente` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`log_cliente` (
  `idlog` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idlog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BANCO`.`log_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_BANCO`.`log_transaccion` ;

CREATE TABLE IF NOT EXISTS `DB_BANCO`.`log_transaccion` (
  `idlog_transaccion` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idlog_transaccion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
